# Generated by Django 4.2.5 on 2024-07-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_db_aianalysislog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aianalysislog",
            name="confidence",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aianalysislog",
            name="image_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="aianalysislog",
            name="message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="aianalysislog",
            name="request_timestamp",
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="aianalysislog",
            name="response_timestamp",
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="aianalysislog",
            name="returnclass",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="aianalysislog",
            name="success",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
