# Generated by Django 4.2.5 on 2024-07-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_aianalysislog_request_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aianalysislog",
            name="request_timestamp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aianalysislog",
            name="response_timestamp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
